### PR TITLE
Update for Spigot 1.8 and fix some exceptions

### PR DESCRIPTION
**Pull request by leMaik**
After updating our lobby server to 1.8, BPC still worked but spammed the console with many class not found exceptions. So this is my pull request, it updates spigot dependencies and repository, adds some refactorings to the code (i.e. remove calls to deprecated methods) and, of course, fixes the exceptions.

### CODE REVIEW

**Comment by alphartdev** [comment]
Hi thanks for the big PR. 
I already updated BPC to 1.8.3 (though didn't push the changes as I need some testing). I'm currently waiting for some update on testing and then I'll push the changes.

**Comment by leMaik** [comment]
Allright, no problem. A development branch for such unstable commits would be a great thing to have. :) I'll stick with my version until the update is ready. Thank's for maintaining the plugin!

**Comment by alphartdev** [comment]
Yeah to be honest I still struggle a lot with git and therefore I don't really know how to setup all that. I should do some testing to train myself. Anyway thanks again for the PR

**Comment by alphartdev** [comment]
That was an old PR. Since this has been posted, BPC has updated to 1.8

**Pull request closed without merging**
